# Include here the items that are repairable
items:
  - 'WOODEN_SWORD'
  - 'WOODEN_SHOVEL'
  - 'WOODEN_HOE'
  - 'WOODEN_AXE'
  - 'WOODEN_PICKAXE'

  - 'STONE_SWORD'
  - 'STONE_SHOVEL'
  - 'STONE_HOE'
  - 'STONE_AXE'
  - 'STONE_PICKAXE'

  - 'CHAINMAIL_BOOTS'
  - 'CHAINMAIL_CHESTPLATE'
  - 'CHAINMAIL_HELMET'
  - 'CHAINMAIL_LEGGINGS'

  - 'LEATHER_BOOTS'
  - 'LEATHER_CHESTPLATE'
  - 'LEATHER_HELMET'
  - 'LEATHER_LEGGINGS'

  - 'IRON_SWORD'
  - 'IRON_HELMET'
  - 'IRON_CHESTPLATE'
  - 'IRON_LEGGINGS'
  - 'IRON_BOOTS'
  - 'IRON_SHOVEL'
  - 'IRON_HOE'
  - 'IRON_AXE'
  - 'IRON_PICKAXE'

  - 'GOLD_SWORD'
  - 'GOLD_HELMET'
  - 'GOLD_CHESTPLATE'
  - 'GOLD_LEGGINGS'
  - 'GOLD_BOOTS'
  - 'GOLD_SHOVEL'
  - 'GOLD_HOE'
  - 'GOLD_AXE'
  - 'GOLD_PICKAXE'

  - 'DIAMOND_SWORD'
  - 'DIAMOND_HELMET'
  - 'DIAMOND_CHESTPLATE'
  - 'DIAMOND_LEGGINGS'
  - 'DIAMOND_BOOTS'
  - 'DIAMOND_SHOVEL'
  - 'DIAMOND_HOE'
  - 'DIAMOND_AXE'
  - 'DIAMOND_PICKAXE'

  - 'NETHERITE_SWORD'
  - 'NETHERITE_HELMET'
  - 'NETHERITE_CHESTPLATE'
  - 'NETHERITE_LEGGINGS'
  - 'NETHERITE_BOOTS'
  - 'NETHERITE_SHOVEL'
  - 'NETHERITE_HOE'
  - 'NETHERITE_AXE'
  - 'NETHERITE_PICKAXE'

  - 'ELYTRA'
  - 'SHEARS'
  - 'TRIDENT'

# Include here the items used to repair
materials:
  - 'OAK_PLANKS'
  - 'BIRCH_PLANKS'
  - 'ACACIA_PLANKS'
  - 'JUNGLE_PLANKS'
  - 'SPRUCE_PLANKS'
  - 'DARK_OAK_PLANKS'
  - 'MANGROVE_PLANKS'
  - 'WARPED_PLANKS'
  - 'CRIMSON_PLANKS'

  - 'COBBLESTONE'
  - 'BLACKSTONE'
  - 'COBBLED_DEEPSLATE'

  - 'GOLD_INGOT'
  - 'IRON_INGOT'
  - 'DIAMOND'
  - 'NETHERITE_INGOT'

  - 'LEATHER'
  - 'PHANTOM_MEMBRANE'
  - 'PRISMARINE_CRYSTALS'

#cofigurable values
maxCost: 25
#this determines the cost of repairing, at this value, the cost for 4 materials is 14 levels, at 6.2 it is 19 levels.
costCoefficient: 4.5